### ISSUE TITLE
deleteProperty

### ISSUE THREAD

**Issue by eriktor** [GoogleChrome/proxy-polyfill#27]
Hi,

Will there be any support soon for the deleteProperty trap?

**Comment by samthor** [comment]
Probably not, sorry. Even though say—instead of [seal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/seal), I could use [preventExtensions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions) to allow deletions, there's no way to _listen_ to those changes or intercept them (we use [defineProperty](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), which only lets you provide a get or set handler, not a 'delete' handler).
