### ISSUE TITLE
Better support for arrays

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/proxy-polyfill#5]
It's possible that we could implement a limited polyfill for array types that doesn't require them to be sealed (i.e., made immutable).

**Comment by Qix-** [comment]
Jumping in here; not a maintainer of this.

I doubt it. Arrays are similar to objects insofar that they do not trigger any sort of event, nor do they have a property (i.e. `Object.defineProperty()`) function for new members being added (one of the reasons why proxies were conceived in the first place).

The closest you could probably get is to override `push()` though that's kind of cheap and wouldn't be incredibly useful seeing as how passing that array to a third party function that uses subscript operators wouldn't properly handle it.

If you could solve this problem with pure ES5, it'd be a huuuuge breakthrough that developers have been trying to solve for a while now.

The closest I've ever seen is registering Proxy objects in a central registry and checking for updates to them on each animation frame/tick (as close to event loop parity as possible) and manually trigger events. The drawbacks to this method, however, are quite obvious.

**Comment by samthor** [comment]
Thanks for the detailed thoughts. I had a few different thoughts about how to do this, all of which you've covered and pointed out why they're not possible :)
(custom `Array` methods => fine, but sealed is sealed)
(setting property descriptors on every index => changes original object, and still can't observe changes)

**Comment by Qix-** [comment]
Sorry I killed the vibe D: :dancer:

**Comment by ElliotNB** [comment]
@samthor Would you potentially be willing to accept a pull request that does the following:

- No longer seal arrays, but all other objects remain sealed.
- Apply wrappers to the `push()`, `pop()`, `shift()`, `unshift()`, `splice()` methods (only on the array instance, `Array.prototype` remains intact).

It's not necessary to wrap `sort()` and `reverse()` because if you don't seal the array, those two methods already work properly with the commit I submitted.

Here's what one of the wrappers might look like (just a rough draft, final would be more condensed and streamlined):

```javascript
proxy.unshift = function() {
    target.length = proxy.length = target.length + 1;
    let prop = target.length-1;
    const desc = {
        enumerable: true,
        configurable: true,
        get: getter.bind(target, prop),
        set: setter.bind(target, prop),
    };
    Object.defineProperty(proxy, prop, desc);
    var returnValue = Array.prototype.unshift.apply(this,arguments);
    proxy.length = target.length;
    return returnValue;
};
```

I try to preserve the native behavior of `.apply()` while using `.length` to adjust the size of `target` and `proxy` enabling us to define `get` and `set` handlers on the array item that will be populated after the `unshift()` executes. Once `Array.prototype.unshift` is invoked, all of the items on `target` bump up by one. `proxy` is one item too long at this point, so we remove the last item via `.length`.

So far this approach seems to mimic ES6 `Proxy` behavior almost identically. The limitations are `.length` cannot be observed and if external code has applied their own `Array` method wrappers, then they might not play nice.

I'm going to build out these wrappers for my own usage, but I thought I'd run it by you first and see if it's something you'd be willing to consider for a pull request.

**Comment by samthor** [comment]
The issue that stopped me from doing this is that this is totally valid in JS:

```js
const x = [true];
x[100] = true;
// now x.length is 101
```

And AFAIK it's impossible to proxy/stub/etc the behavior behind that. I like the rest of your thoughts, and maybe there's a valid compromise, but do you have any other ideas? (maybe a flag in `handlers` to enable this mode, with this as a caveat).

**Comment by ElliotNB** [comment]
@samthor Yeah I don't think there's a way to account for that. If it were possible to observe `.length` mutations in ES5, then we'd be in business, but without `.length` there aren't any options I can think of.

That said, I think it might be helpful to support the major array mutation methods, but warn in the readme that the polyfill doesn't support `.length` assignments or an assignment to an out of bound index.

I think a flag in `handlers` to enable enhanced array support is a great idea. Probably not often, but some users definitely won't want their array mutation methods modified.

FWIW, some of the major JS frameworks, such as VueJS, have the same limitations for their [array change detection](https://vuejs.org/v2/guide/list.html#Array-Change-Detection) capabilities. Seems like everyone has run up against this same brick wall in ES5.

**Comment by ElliotNB** [comment]
@samthor Just thought I'd poke my head in here again -- I forked this Proxy polyfill for another project wrote wrapper methods for all Array mutation methods (`push`, `pop`, `shift`, etc). It has been working very well for us in a variety of web apps in production. You can't intercept all types of Array mutation methods (i.e., mutations via `.length` or your example above), but you can monitor everything else. 

Please let me know if this is something you'd be interested adding to the Proxy polyfill (perhaps enabled only via a special flag in the handlers as you suggested) and I'd be happy to send in a pull request!
